language: c++

os:
  - linux
  - osx

dist: xenial
sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev libglew-dev ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake . ;
    else
      CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake . ;
    fi
  - make -j2

deploy:
  - provider: releases
    api_key: "${token}"
    file:
      - "Linux.zip"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME != "osx"
  - provider: releases
    api_key: "${token}"
    file:
      - "Macos.zip"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME == "osx"